language: java
env:
  global:
  - CC_TEST_REPORTER_ID=a0dddeda8363cade8544d0079ff5992b9584fd68998b823524f279a0ef8026c8
  - secure: Q/HyLMhXjvIwuAucreHPcQdiDJ4FwfxhrhieV1JpjJqyfCqiZV2bkRmx68tDTEQzxusCbA9vxQ6tDRdSxawoTFdhFGNc65++nA1mqCDZfB+lng8BWY7Is+Oelkv6qTbrbanxlbNN3bqj3HjiiRmXl6GIPA9YyC4BWOxNrc78CqKBCoFR9BalolXh7P/qtqVIM9dM9tkPisStwk1Gc+/GdrtE5sKd1CDWWGW7wjVw1UxkDJmK3XgSbubMlWcSwKgooUqwzmEeNSlVsa7JoBPf4TT4KBYbndODXcvsfGKSu6ANdJ7LgtyuwEAyjPW9Zu48W4zs1THaAlGoU/MQG179dZESDJtmMuNzJX0Lp3flZNE/q621uZ9Yd1ODlYuo53ZWtwvedNCsOneDEMUEOi2nK3TOoqAdg0Ei1pirv5Zs2AmhpJ356UDoC0WTTBUkb9w2bDS2Ik/LIHoTVhkGubkuyvsHcWBXN+cMnUzT+jMilqPE84bzAtXPBLkyDYkcTQC37fBgNYbfb6OxEga+E0oV0sO/fc4EhXYlOP3VZqCUzF3ZlxUtSvdYeGXekozTEd5Q25QZQYNyvEfAoEXAKNxIZXV3ZHbfpEGrLduLfvlw5YXOI8n1VPF6WUtnjQAZQLTmJo1cagKNTSy8iRUng+y9IaLvXCty0zUGwpJf30N36gU=
  - secure: Cq4nalF1yHD2UPt3L4I140SCypITzXGmjx81OK2UMY5XsxJH9VtugqA0TFqTRDqA50ZaYZ0+8dWgLYo/nLAdXX2j3TKeqHgPekJ2VbBo9TjRdW6PXq/ANdYKGuZP9eVBu36imB+2WFD2Y50XlMraBL+H/0qer3dPNvEGKjUdQ+pTEf6Ek8cNbURVZbCoGqtDHv475oBkC0XJjM/yAV3XjdNFLRNpwXkccR4IqpSXtwYYqc71FtKriQ1p14/pAbxKqY3xWiWoSdG1nVp6fwfDFZOEWHXRqZcU4QhffF0gelYhob8vcBjW9F3rwTxPhJrNhkUR7KGmdp06d0+C7BZDQdAwG/QaafjvFn159dXclTWGs0jeKtg5IBcCgk3GPZxjfxGNBUBQ3DkNyZZM2iE0JvAlZXUOYk1IOFAzazk1OBcNMAndZHokNAzyXlQcvrQoC3BjSUZX2RR8JVljvq+xlqnNowgAwigWQLhp5kJ8WkMk9iQFYFXd35kE87+mA4rd7MpBQuNyQfK9xHiUiRnNEIAMSM9TTg4qUPT/zdBLH70x/5rUAANTLPRgunujBQDKn1tZXwg55FdzTEplzAwULF7cg7NHQGMGrFt3GErFEWruPqtw7IXNNBdGuFMoUpZSBqDASpzaAjL30/dH6cQdnQap1oAQOYy+8SXxj4N0W5w=
  - secure: 0IbOeCg7rFH902fMw4FTnjI9OEkNQbihjGVrGIZiY5HSvCW6E+wWC3DqM7x93Bak0+i03dKEA2UMHvFg9l/4fiUd1noEOP7xkonjLVALOnbNWCUJRbTaovtKO4YPgLWtnocEuTMkxhjPE2JnN827OL9wsIEgGaQrpjdwRKkrQxJ0Fglu9oXatXThXE9BBHI0D6mvuXoHJAR0DoVhW/P6IR/ILOdd3K3jJCK3VV0JgHeYtRMalF5EEIRBuLPuBhintbQOkUTSKipNG9jpdZeY/6y5fuD/jhoW5xMM0cq35zxzH2oJbbMjPImXPBS/5NEl/PQbkDUjZ+5glfqyjm9gqoaSIe0qi9yQ93+gRVbmmghpbvuV7Ikp2nP4khdXlaaP1m6SosSfbBavtEqKmZT3jXrdfB1kvZINj1QaLzom1oiFCu7Y+rxuW4gZZSaxCkr55wcX6Qvaf4QTT0AAhr1F3ENAq1mcAwvxZk9qmDnB1H3+nXyrGy7hqg9u/N3y4gWZqdohZl7I0qqNdokzmUcfwYWJTvFKo1333cdqegUUQFc//S05NxKzX5u5Z3XJ7HtmYKkycoxoclfmc9iJUDl4T8tDTa+ojixw3bM0sPXs3Y6YljvV8RecAWV/LFNrxwHEu7xqIQXK616BTVdeILC4b7KPbI6eLiKSt86y7GCJvD8=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_BRANCH ~= ^[\d]+\.[\d]+(\.[\d]+)?$
    all_branches: true
- provider: releases
  api_key:
    secure: IN+w9/eDXynx3EM4TgRj4IwMC0+s5Di+IBEG9no51hUiR2avPc72k+qHmxJWiN3of9CX0mCdwgm+KhD2uKSZLnw+HadWb2ZtSMADfzoffQQb9eLkmDsVQbgQ1C4FWxLKfGl3DfMiw2cDr7NsD75sLU07EYC3SMWPuGYCDrf5NVeYPhb8StCA61noKwBQh3W1NMy20XJYE+fuaV9e3Ehl20wtpVVF5DweQVsAcXMJ8uS0ndtUHZs3BNLULSNRa7Pm46trD/RoI1foRGTmXrBBtC/5RPoI85TUhgeYJp7MmoCLfLDKt6IvqnmL/UvgTL3Hr8v/0vvgVtR/I7RZ4B1vvyPsxRkMWkqqm2hEpmGkbYxO2UEBo3yTAob4aocG0YYwaHF/IHubV8cya+lRWbTvaoFoIFNUZgFlqyt0X9JBFQr7aaEI6LlhiSwsQpz7Lok4ofIQRKnAOtbyoDpB7oLZwYFS58ZqYar6yk7CuKnkoZSB9jqPzL+xxU1Ccf07T7E5YbDKvuJv/KFwD0xLALkWadeTxMLPVjoE4axzXiBXd/gl4QebpWT3eIBZAF9HrX2SkrKhquECOSaBTJNnXqM5B/jc6CkQwAcjycIZuPNoyk3r00OPWq5Li4xKkxKjATtTmwBf3XeTHqXwpuCeEBsbOpUkxhzv2GMK7R8nZtOAItU=
  file: ".travis.yml"
  on:
    repo: trickl/assertj-json
